algoritmo "ZeroPara"
//Faça um algoritmo que solicite N números inteiros até que o número 0(zero) seja digitado.
//Ao final o algoritmo deve informar o maior e o menor número digitado.
var

N:inteiro

inicio

   escreva("Digite um numero: ")
   leia(N)
   
   enquanto (N<>0) faca
   escreva("Digite um numero: ")
   leia(N)
   fimenquanto
   
   escreval("A repetição foi encerrada!!!")


fimalgoritmo
